import pandas as pd
import sys

# Load the data generated by your shell script
file_path = 'system_health.csv'
try:
    df = pd.read_csv(file_path)
except FileNotFoundError:
    print("Error: CSV file not found. Run the shell script first!")
    sys.exit()

# --- THE LOGIC: Statistical Anomaly Detection ---
# We calculate the Mean (average) and Standard Deviation (variation).
# If a data point is > (Mean + 2 * StdDev), it is statistically an anomaly (top 5% outlier).
cpu_mean = df['CPU_Percent'].mean()
cpu_std = df['CPU_Percent'].std()

# Define a dynamic threshold (or set a hard limit like 80.0)
cpu_threshold = cpu_mean + (2 * cpu_std)

# Just for this demo, let's ensure the threshold isn't too low if the system is idle
if cpu_threshold < 10:
    cpu_threshold = 50.0

# Get the latest reading (the last row)
latest = df.iloc[-1]

print(f"\n--- SYSTEM HEALTH REPORT : {latest['Timestamp']} ---")
print(f"Current CPU: {latest['CPU_Percent']}% (Threshold: {cpu_threshold:.2f}%)")

# Check for Anomalies
if latest['CPU_Percent'] > cpu_threshold:
    print("⚠️  ALERT: CPU Usage is abnormally high!")
elif latest['CPU_Percent'] > 80:
    print("⚠️  ALERT: CPU is critically high (Rule-based)!")
else:
    print("✅  System Status: NORMAL")

print("-" * 40)
